branch-defaults:
  master:
    environment: cuwebenv
    group_suffix: null
global:
  application_name: cuweb
  branch: null
  default_ec2_keyname: adumatta
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
