"""empty message

Revision ID: 1b18f5ba1d9a
Revises: 93ae30e26c9e
Create Date: 2023-11-08 14:37:25.280625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b18f5ba1d9a'
down_revision = '93ae30e26c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicantIdentity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('usercode', sa.String(), nullable=False),
    sa.Column('identitytype', sa.String(), nullable=True),
    sa.Column('identitynumber', sa.String(), nullable=True),
    sa.Column('identityexpire', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicantIdentity')
    # ### end Alembic commands ###
