"""empty message

Revision ID: 43c0ec9d27c3
Revises: cacd7a5dd0e8
Create Date: 2023-11-06 12:03:35.611574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c0ec9d27c3'
down_revision = 'cacd7a5dd0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicantContacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('usercode', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('applicanteducation', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('programs', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'date_created')
    op.drop_column('applicanteducation', 'date_created')
    op.drop_table('applicantContacts')
    # ### end Alembic commands ###
