"""empty message

Revision ID: 68acf3ea3956
Revises: c8871360c068
Create Date: 2023-10-30 11:51:15.724872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68acf3ea3956'
down_revision = 'c8871360c068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
