"""empty message

Revision ID: 6adf79447673
Revises: 83430a0ad34b
Create Date: 2023-01-21 11:14:00.188444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adf79447673'
down_revision = '83430a0ad34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicanteducation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.DateTime(), nullable=False))
        batch_op.drop_column('othername')
        batch_op.drop_column('nationality')
        batch_op.drop_column('stream')
        batch_op.drop_column('date_created')
        batch_op.drop_column('surname')
        batch_op.drop_column('email')
        batch_op.drop_column('campus')
        batch_op.drop_column('phone')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicanteducation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('campus', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('stream', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('othername', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('endDate')
        batch_op.drop_column('start')
        batch_op.drop_column('school')

    # ### end Alembic commands ###
