"""empty message

Revision ID: 7598286e0325
Revises: ffa813972e05
Create Date: 2023-01-22 16:37:10.158931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7598286e0325'
down_revision = 'ffa813972e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indexNumber', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exam', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('exam')
        batch_op.drop_column('indexNumber')

    # ### end Alembic commands ###
