"""empty message

Revision ID: 787d34ccea7d
Revises: 1b18f5ba1d9a
Create Date: 2023-11-08 15:03:03.543091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787d34ccea7d'
down_revision = '1b18f5ba1d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('school', sa.String(), nullable=True))
    op.add_column('examResult', sa.Column('school', sa.String(), nullable=True))
    op.drop_column('examResult', 'indexNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examResult', sa.Column('indexNumber', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('examResult', 'school')
    op.drop_column('exam', 'school')
    # ### end Alembic commands ###
