"""empty message

Revision ID: 79fed1ced724
Revises: 7598286e0325
Create Date: 2023-01-23 08:54:35.999473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fed1ced724'
down_revision = '7598286e0325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examResult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('usercode', sa.String(), nullable=False),
    sa.Column('indexNumber', sa.String(), nullable=True),
    sa.Column('exam', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examResult')
    # ### end Alembic commands ###
