"""empty message

Revision ID: 83430a0ad34b
Revises: 93d843fe7664
Create Date: 2023-01-21 11:12:33.527251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83430a0ad34b'
down_revision = '93d843fe7664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicanteducation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('usercode', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('othername', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('campus', sa.String(), nullable=False),
    sa.Column('stream', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('entry_mode', sa.String(), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicanteducation')
    # ### end Alembic commands ###
