"""empty message

Revision ID: 924c6473309d
Revises: 
Create Date: 2023-01-15 22:08:51.335436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924c6473309d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('code', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.drop_column('telegramBot')
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('balance')
        batch_op.drop_column('chatId')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('chatId', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('telegramBot', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('paid')
        batch_op.drop_column('date_created')
        batch_op.drop_column('code')
        batch_op.drop_column('name')

    op.drop_table('payments')
    # ### end Alembic commands ###
