"""empty message

Revision ID: 93ae30e26c9e
Revises: 43c0ec9d27c3
Create Date: 2023-11-06 12:07:24.346022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ae30e26c9e'
down_revision = '43c0ec9d27c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicantContacts', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('exam', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('guardian', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guardian', 'date_created')
    op.drop_column('exam', 'date_created')
    op.drop_column('applicantContacts', 'date_created')
    # ### end Alembic commands ###
