"""empty message

Revision ID: 93d843fe7664
Revises: 4bb4705ac9f8
Create Date: 2023-01-21 10:23:47.085060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d843fe7664'
down_revision = '4bb4705ac9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicantinformation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('usercode', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicantinformation', schema=None) as batch_op:
        batch_op.drop_column('usercode')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
