"""empty message

Revision ID: 96b0e1efd34a
Revises: c7c9d655aced
Create Date: 2023-11-01 13:18:33.313470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b0e1efd34a'
down_revision = 'c7c9d655aced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicantinformation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicantinformation', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
