"""add admission records

Revision ID: aa6ae78bbbd
Revises: cae3122b56bc
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'aa6ae78bbbd'
down_revision = 'cae3122b56bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissionrecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('campus', sa.String(), nullable=False),
    sa.Column('stream', sa.String(), nullable=False),
    sa.Column('program_offered', sa.String(), nullable=False),
    sa.Column('admission_type', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admissionrecords')
    # ### end Alembic commands ###
