"""empty message

Revision ID: b7f4259fb042
Revises: 783ba71359d7
Create Date: 2023-10-27 18:00:07.417372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f4259fb042'
down_revision = '783ba71359d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstchoice', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('seconschoice', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thirdchoice', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('thirdchoice')
        batch_op.drop_column('seconschoice')
        batch_op.drop_column('firstchoice')

    # ### end Alembic commands ###
