"""empty message

Revision ID: ff07e436beb5
Revises: 787d34ccea7d
Create Date: 2023-11-08 15:12:07.644699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff07e436beb5'
down_revision = '787d34ccea7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicantReferees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('usercode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('email', sa.DateTime(), nullable=True),
    sa.Column('job', sa.DateTime(), nullable=True),
    sa.Column('filed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicantReferees')
    # ### end Alembic commands ###
